# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBookPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=128)),
                ('phone_number_1', models.CharField(blank=True, help_text='Выберите или добавьте номер в формате (0__)___-__-__', max_length=25, verbose_name='Телефон 1')),
                ('phone_number_2', models.CharField(blank=True, help_text='Выберите или добавьте номер в формате (0__)___-__-__', max_length=25, verbose_name='Телефон 2')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')),
                ('region', models.CharField(help_text='Выберите или добавьте область проживания. Например: Киевская область', max_length=50, verbose_name='Область')),
            ],
            options={
                'verbose_name_plural': 'Контактные лица',
                'verbose_name': 'Контактное лицо',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
                'verbose_name': 'Номер телефона',
                'ordering': ('phone_number',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Области',
                'verbose_name': 'Область',
                'ordering': ('region',),
            },
        ),
    ]
