# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=50, unique=True, verbose_name='Область'),
        ),
    ]
